# Generated by Django 3.1.7 on 2021-07-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='texte',
            field=models.TextField(default='...'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='Alphonse Muhindo Valivambene', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='email',
            field=models.EmailField(default='valivambenealphonse@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='....', max_length=100),
        ),
    ]
